/**
 * Album Model
 * --------------------
 * Stores categorized collections of media.
 */

import mongoose from 'mongoose';

const albumSchema = new mongoose.Schema({
  eventId: { type: mongoose.Schema.Types.ObjectId, ref: 'Event', required: true },
  name: { type: String, required: true },
  description: { type: String },
  media: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Media' }],
  visibility: { type: String, enum: ['public', 'private'], default: 'public' },
  isAutoGenerated: { type: Boolean, default: false }, // System-created albums
  createdAt: { type: Date, default: Date.now },
});

export default mongoose.model('Album', albumSchema);
